SELECT TPfc.CntyCd, TPfc.BatchDt, TPfc.BatchSeq, TPfc.TransId, T.MtgSeq
,TPfc.MuncCd as [MUNICIPALITY CODE]
,TPfc.InputPclMatchKey as [APN (Parcel Number)]
--,'' AS [APN SEQUENCE NUMBER]
,TPfc.BatchDt AS  [BATCH-DT]
,TPfc.BatchSeq AS [BATCH-SEQ]
,TPfc.DocYyDt  AS [DOCUMENT YEAR]                         
--,'' AS   [SALE AMOUNT]                         
--   ,'' AS [MORTGAGE AMOUNT]                      
--,''  AS [SALE DATE  (YYYYMMDD)]
,TPfc.RecordingDt  AS [RECORDING DATE  (YYYYMMDD)]
,TPfc.DeedCatTyp  AS [DOCUMENT TYPE]
--,'' AS [TRANSACTION TYPE]
,TPfc.DocNbr AS [DOCUMENT NUMBER]
,TPfc.RecordingBook+TPfc.RecordingPage AS [BOOK/PAGE  (6x6)]
--,'' AS  [SALE CODE]
,TPfc.DocTyp AS [DETAILED DOCUMENT TYPE]
,TPfc.MultiSplitCd AS [MULTI APN]
,TPfc.MultiPropCnt  AS  [MULTI APN COUNT]
,TPfc.TitleCompanyCd AS [TITLE COMPANY CODE]
,TPfc.SecDCResModelInd AS [RESIDENTIAL MODEL INDICATOR]
--,'' AS [MORTGAGE DATE]
--,'' AS [MORTGAGE LOAN TYPE CODE]
--,'' AS [MORTGAGE DEED TYPE]
--,'' AS  [MORTGAGE TERM CODE]
--,''AS [MORTGAGE TERM]
--,'' AS [MORTGAGE DUE DATE]
--,'' AS [MORTGAGE ASSUMPTION AMOUNT]
--,'' AS [MORTGAGE CHANGE AMOUNT]
,TPfc.AbsenteeIrisCd AS [ABSENTEE INDICATOR]
,TPfc.PartialInterestTransferInd  AS  [PARTIAL INTEREST INDICATOR]     
--,'' AS  [OWNERSHIP TRANSFER PERCENTAGE]       
,TPfc.PrimaryCatCd AS [PRI-CAT-CODE]
--,'' AS [MORTGAGE INTEREST RATE TYPE]
,TPfc.TitleCompanyNm AS [TITLE COMPANY NAME]
--,'' AS [SELLER CARRY BACK ('Y')]
--,'' AS [PRIVATE PARTY LENDER ('Y')]
--,'' AS [CONSTRUCTION LOAN ('Y')]
,TPfc.SecDCResaleInd AS [RESALE/NEW CONSTRUCTION]
,TPfc.SecDCInterrelatedInd AS  [INTER FAMILY ('Y')]
,TPfc.SecDCArmsLengthMortgageInd AS [CASH/MORTGAGE PURCHASE]
,TPfc.SecDCRealEstateOwnedInd AS   [FORCLOSURE ('Y')]
--,'' AS [REFI FLAG ('Y')]
--,'' AS [EQUITY FLAG ('Y')]
,TPfc.CntyRgnId AS [County Region ID]
--,'' AS [MORTGAGE DOCUMENT NUMBER]
--,'' AS [MORTGAGE BOOK/PAGE  (6x6)]
--,'' AS [MORTGAGE INTEREST RATE]
,TPfc.OrigRecordingDt AS [ORIGINAL RECORDED DATE]
,TPfc.OrigRecordingPage+TPfc.OrigRecordingBook AS [ORIGINAL BKPG]    
,TPfc.OrigDocNbr AS [ORIGINAL DOC NUMBER]
,TPfc.SourceInd AS [SALES SOURCE INDICATOR]
--,'' AS [DOC TRANSFER TAX] 
,TPfc.SecDCRealEstateOwnedSaleInd AS [REO SALE]
--,'' AS [OTHER SUBORDINATE LOANS]
--,'' AS [RMS EQUITY FLAG TYPE]
,TPfc.ChronoNbr AS [CHRONOLOGY NUMBER]
,TPfc.UpdateTimestamp AS [TIMESTAMP DATE]
,TPfc.UpdateTimestamp AS [TIMESTAMP TIME]
,TPfc.EditCounter AS [RECORD TYPE - ADD, CHANGE, DELETE]
,TPfc.CaseNbr AS [COURT CASE #]
,TPfc.PclMatchCd AS [PARCEL FILE MATCH CODE]
,TPfc.DistCd AS [DISTRICT CODE]
,TPfc.CntySectionCd AS [SECTION]
,TPfc.TitleOrderNbr AS [TITLE ORDER NUMBER]
,TPfc.TitleOrderAbbrev AS [TITLE ORDER ABBREVIATION]
,TPfc.EscrowOrderNbr AS [ESCROW ORDER NUMBER]
,TPfc.EscrowOrderAbbrev AS [ESCROW ORDER ABBREVIATION]
,TPfc.TimeshareOrderNbr AS [TIMESHARE/TRUSTEES ORDER (SALE) NUMBER]
,TPfc.TimeshareOrderAbbrev AS [TIMESHARE/TRUSTEES SALE ABBREVIATION]
,TPfc.TitleOrderAccomodationInd AS [ACCOMMODATION RECORDING FLAG]
,TPfc.BeneficiaryPurchasedInd AS [GRANTEE THE FORECLOSING BENEFICIARY]
,TPfc.OrigDocDt AS [RECORDING DATE OF ORIGINAL MTG]
,TPfc.LandCourtDocNum AS [HAWAII LAND COURT DOCUMENT NUMBER]
,TPfc.CertificateNbr AS [HAWAII TCT/CERTIFICATE NUMBER]
,TPfc.ExciseTaxNbr AS [WA EXCISE NUMBER]
,TPfc.PropStatusCd AS [AZ EXEMPTION SUFFIX]
,TPfc.PropStatusCd AS [AZ EXEMPTION PREFIX]
,TPfc.CashDownAmt AS [Cash Down Amount]
,TPfc.PclidIrisFrmtd AS [APN PARCEL NUMBER FORMATTED - IRIS]
,TPfc.AvmValAmt as [HPI VALUE AMT ]
,TPfc.AuctionDt as [ANTICIPATED FORECLOSURE SALE DATE]
,TPfc.LisPendensTyp as [LIS PENDENS TYPE]
,TPfc.DefaultDt as [DATE OF DEFAULT]
,TPfc.DefaultAmt as [AMT OF DEFAULT ]
,TPfc.FirstMissedPaymentDt as [DUE ON DATE/FIRST MISSED PAYMENT DATE]
,TPfc.DocFilingDt as [FILING DATE]
,TPfc.AuctionAddr as [STREET ADDRESS OF AUCTION CALL]
,TPfc.AuctionStCd as [STATE OF AUCTION CALL]
,TPfc.AuctionTime as [AUCTION TIME]
,TPfc.AuctionCityName as [CITY OF AUCTION CALL]
,TPfc.FinalJudgmntAmt as [UNPAID BALANCE (FINAL JUDGMENT AMT)]

FROM Trans.vTransPreForeClosure TPfc INNER JOIN Trans.vTrans T on TPfc.CntyCd=T.CntyCd AND 
TPfc.BatchDt=T.BatchDt AND TPfc.BatchSeq=T.BatchSeq AND TPfc.TransId=T.TransId
where TPfc.CntyCd='01003'