SELECT TLi.CntyCd, TLi.BatchDt, TLi.BatchSeq, TLi.TransId, TLi.MtgSeq 
,TLi.MuncCd as [MUNICIPALITY CODE]
,TLi.PclId as [APN (Parcel Number)]
,TLi.PclSeqNbr AS [APN SEQUENCE NUMBER]
,TLi.BatchDt AS    [BATCH-DT]
,TLi.BatchSeq AS [BATCH-SEQ]
,TLi.DocYyDt AS  [DOCUMENT YEAR]
--,'' AS   [SALE AMOUNT]                                     
,TLi.MtgAmt AS [MORTGAGE AMOUNT]
,TLi.SaleDt  AS [SALE DATE  (YYYYMMDD)]
,TLi.RecordingDt  AS [RECORDING DATE  (YYYYMMDD)]
,TLi.DeedCatTyp  AS [DOCUMENT TYPE]
,TLi.TransTyp AS [TRANSACTION TYPE]
,TLi.DocNbr AS [DOCUMENT NUMBER]
,TLi.RecordingBook+TLi.RecordingPage AS [BOOK/PAGE  (6x6)]
--, '' AS  [SALE CODE]
,TLi.DocTyp AS [DETAILED DOCUMENT TYPE]
,TLi.MultiSplitCd AS [MULTI APN]
,TLi.MultiPropCnt AS  [MULTI APN COUNT]
,TLi.TitleCompanyCd AS [TITLE COMPANY CODE]
,TLi.SecDCResModelInd AS [RESIDENTIAL MODEL INDICATOR]
,TLi.MtgDt AS [MORTGAGE DATE]
,TLi.MtgLoanTypCd AS [MORTGAGE LOAN TYPE CODE]
,TLi.MtgDocTyp AS [MORTGAGE DEED TYPE]
,TLi.MtgTermCd AS  [MORTGAGE TERM CODE]
,TLi.MtgTermAmt AS [MORTGAGE TERM]
,TLi.MtgDueDt AS [MORTGAGE DUE DATE]
,TLi.MtgAssumpAmt AS [MORTGAGE ASSUMPTION AMOUNT]
,TLi.MtgChangeAmt AS [MORTGAGE CHANGE AMOUNT]
,TLi.AbsenteeIrisCd AS [ABSENTEE INDICATOR]
--,'' AS  [PARTIAL INTEREST INDICATOR]
--,'' AS  [OWNERSHIP TRANSFER PERCENTAGE]
,TLi.PrimaryCatCd AS [PRI-CAT-CODE]
,TLi.MtgIntRateTyp AS [MORTGAGE INTEREST RATE TYPE]
,TLi.TitleCompanyNm AS [TITLE COMPANY NAME]
,TLi.SecMCSellerCarriedLoanInd AS [SELLER CARRY BACK ('Y')]
,TLi.SecMCPrivatePartyLoanInd AS [PRIVATE PARTY LENDER ('Y')]
,TLi.SecMCConstructionLoanInd AS [CONSTRUCTION LOAN ('Y')]
,TLi.SecDCResaleInd AS [RESALE/NEW CONSTRUCTION]
,TLi.SecDCInterrelatedInd AS  [INTER FAMILY ('Y')]
,TLi.SecDCArmsLengthMortgageInd AS [CASH/MORTGAGE PURCHASE]
,TLi.SecDCRealEstateOwnedInd AS   [FORCLOSURE ('Y')]
,TLi.SecMCRefinanceLoanInd AS [REFI FLAG ('Y')]
,TLi.SecMCEquityLoanInd AS [EQUITY FLAG ('Y')]
,TLi.CntyRgnId AS [County Region ID]
,TLi.MtgDocNbr AS [MORTGAGE DOCUMENT NUMBER]
,TLi.MtgRecordingBook+TLi.MtgRecordingPage AS [MORTGAGE BOOK/PAGE  (6x6)]
,TLi.MtgIntRateCap AS [MORTGAGE INTEREST RATE]
,TLi.OrigRecordingDt AS [ORIGINAL RECORDED DATE]
--,' ' AS [ORIGINAL BKPG]    
,TLi.OrigDocNbr AS [ORIGINAL DOC NUMBER]
,TLi.SourceInd AS [SALES SOURCE INDICATOR]
--,'' AS [DOC TRANSFER TAX] 
,TLi.SecDCRealEstateOwnedSaleInd AS [REO SALE]
,TLi.SecMCOtherSubordLoanInd AS [OTHER SUBORDINATE LOANS]
,TLi.MtgSubordTyp AS [RMS EQUITY FLAG TYPE]
,TLi.ChronoNbr AS [CHRONOLOGY NUMBER]
,TLi.UpdateTimestamp  AS [TIMESTAMP DATE]
,TLi.UpdateTimestamp AS [TIMESTAMP TIME]
,TLi.EditCounter AS [RECORD TYPE - ADD, CHANGE, DELETE]
--, '' AS [COURT CASE #]
,TLi.PclMatchCd AS [PARCEL FILE MATCH CODE]
,TLi.DistCd AS [DISTRICT CODE]
,TLi.CntySectionCd AS [SECTION]
,TLi.TitleOrderNbr AS [TITLE ORDER NUMBER]
,TLi.TitleOrderAbbrev AS [TITLE ORDER ABBREVIATION]
,TLi.EscrowOrderNbr AS [ESCROW ORDER NUMBER]
,TLi.EscrowOrderAbbrev AS [ESCROW ORDER ABBREVIATION]
,TLi.TimeshareOrderNbr AS [TIMESHARE/TRUSTEES ORDER (SALE) NUMBER]
,TLi.TimeshareOrderAbbrev AS [TIMESHARE/TRUSTEES SALE ABBREVIATION]
,TLi.TitleOrderAccomodationInd AS [ACCOMMODATION RECORDING FLAG]
--,'' AS [GRANTEE THE FORECLOSING BENEFICIARY]
,TLi.OrigDocDt AS [RECORDING DATE OF ORIGINAL MTG]
,TLi.LandCourtDocNum AS [HAWAII LAND COURT DOCUMENT NUMBER]
,TLi.CertificateNbr AS [HAWAII TCT/CERTIFICATE NUMBER]
,TLi.ExciseTaxNbr AS [WA EXCISE NUMBER]
--,'' AS [AZ EXEMPTION SUFFIX]
--,'' AS [AZ EXEMPTION PREFIX]
--,'' AS [Cash Down Amount]
,TLi.PclidIrisFrmtd AS [APN PARCEL NUMBER FORMATTED - IRIS]
,TLi.AvmValAmt as [HPI VALUE AMT ]
,TLi.SecMCConformingLoanInd
,TLi.SecMCConventionalLoanInd
,TLi.SecMCFhaLoanInd
,TLi.SecMCFixedRateLoanInd
,TLi.SecMCNonConformingLoanInd
,TLi.SecMCSmallBusAssocLoanInd
,TLi.SecMCVaLoanInd
,TLi.SecMCVariableRateLoanInd
,TLi.SecDCInvestorPurchaseInd
,TLi.SecDCNewConstructionInd
,TLi.SecDCRealEstateOwnedInd
,TLi.SecDCShortSaleInd
,TLi.SecDCArmsLengthCashInd

FROM Trans.vTransLien TLi
WHERE TLi.CntyCd = '01003' AND Tli.DeedTransId IS NULL